In this code, various machine learning algorithms are applied to the "heart.csv" dataset. The dataset is split into features (X) and the target variable (y). Then, the data is split into training and testing sets. The features are standardized using the StandardScaler.

A dictionary named models is created to store the different machine learning models to be evaluated. The code then trains and evaluates each model using the training and testing sets. The evaluation metrics used include accuracy, confusion matrix, and classification report.

After evaluating the models, the code calculates and displays the feature importance ranking using the Random Forest classifier. This provides insights into which features are most influential in predicting the target variable.

You can run this code in a Python environment to apply multiple machine learning algorithms and obtain insights from the "heart.csv" dataset. Feel free to modify the code to include additional models or tweak parameters based on your requirements.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Load the dataset
data = pd.read_csv("/content/drive/MyDrive/heart.csv")

# Split the data into features (X) and target variable (y)
X = data.drop('target', axis=1)
y = data['target']

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a dictionary to store the models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

# Train and evaluate each model
for model_name, model in models.items():
    print(f"================ {model_name} ================")
    # Train the model
    model.fit(X_train_scaled, y_train)

    # Make predictions
    y_pred = model.predict(X_test_scaled)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy: {accuracy:.2f}")

    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix:")
    print(cm)

    classification_rep = classification_report(y_test, y_pred)
    print("Classification Report:")
    print(classification_rep)

    print("\n")

# Feature Importance (Random Forest)
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)
importance = rf.feature_importances_
feature_names = X.columns

# Sort feature importances in descending order
indices = np.argsort(importance)[::-1]

# Print feature importance ranking
print("Feature Importance Ranking:")
for i in range(len(importance)):
    print(f"{i+1}. {feature_names[indices[i]]}: {importance[indices[i]]:.4f}")


================ Logistic Regression ================
Accuracy: 0.85
Confusion Matrix:
[[25  4]
 [ 5 27]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



================ Decision Tree ================
Accuracy: 0.80
Confusion Matrix:
[[27  2]
 [10 22]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.93      0.82        29
           1       0.92      0.69      0.79        32

    accuracy                           0.80        61
   macro avg       0.82      0.81      0.80        61
weighted avg       0.83      0.80      0.80        61



================ Random Forest ================
Accuracy: 0.84
Confusion Matrix:
[[24  5]
